from dataclasses import dataclass


@dataclass(slots=True)
class ReviewComment:
    """
    Represents a review comment generated by the AI.
    """

    filename: str
    comment: str
    severity: str
